# Generated by Django 5.0.7 on 2024-07-17 22:18

import challenge.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[challenge.users.validators.validate_cpf]),
        ),
    ]
